### ISSUE TITLE
Creative Dimlet Workbench

### ISSUE THREAD

**Issue by alucard87pl** [McJty/RFToolsDimensions#22]
It'd be cool if there was a way to get all the dimlets in a creative way.
Using the command line is mighty annoying when just trying to create a quick-and-dirty safe void world to use as a nexus.

Even a simple thing that would enable the user to middle-click dimlets in the Workbench when in creative and get the dimlet without actually crafting the dimlet (getting the normal components is easy, but the essence absorber is a pain)

Mystcraft had it's Creative Book. RFTD could use it's own.

**Comment by marcin212** [comment]
:+1:

**Comment by Vaygrim** [comment]
Yes, please.. all of this. Ever since "RF Tools Dimensions" became its own mod, it is a HUGE pain in the backside to make (in creative) specific dimensions for creative builds.. server resources, etc. Every time I restart my Test Server, I want a void dimension for those wanting to make void bases (useful for folks playing on low powered computers) as well as a server workshop.. plus a "Mining Dimension".

Now making these are a pretty big issue.

**Comment by McJty** [comment]
This will be implemented next release. Not with a creative workbench but with a feature that when you are in creative mode you can shift-click dimlets to cheat them in using the workbench
