### ISSUE TITLE
Dimension Enscriber always has 'inventory' in the name field when opened.

### ISSUE THREAD

**Issue by brisingraerowing** [McJty/RFToolsDimensions#233]
Issue description: 

The dimension enscriber has the word 'inventory' in the name field when the GUI is opened.

Steps to reproduce: 

Open the GUI of a dimension enscriber.

Versions:
* Minecraft: 1.12.2
* Forge: 2760
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 3.0.4
* RFTools: 7.55
* RFTools Dimensions: 5.60

Possibly incompatible mods: None known

Relevant logs, if any:

**Comment by josephcsible** [comment]
@McJty This seems to be a regression caused by https://github.com/McJtyMods/RFToolsDimensions/commit/ef116a2e1c0a134529fc0b1f74ebbdf8a563b215#diff-53cda85097ffc0785101b9debe2d77f3R49 (you have a setName but not a getName, and it just so happens that DefaultSidedInventory has a getName with the right signature that returns "inventory"). I haven't worked with that command system enough to know the best way to fix this. Can you take a look?

**Comment by McJty** [comment]
Fixed next release
