### ISSUE TITLE
RFToolsUtilities unlisted requirement

### ISSUE THREAD

**Issue by techwiz78** [McJty/RFToolsDimensions#426]
Issue description: Matter Transmitter/Receiver required to enter any created dimension despite Utilities not being a required dependency

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.86
* McJtyLib: 6.0.19
* RFTools: 3.0.11
* RFTools Dimensions: 8.0.9

**Comment by McJty** [comment]
That's not an issue. This is by design. It is possible for RFTools Dimensions to be used by pack makers for custom dimensions where they provide another way to go to that dimension

**Comment by Waterspark63** [comment]
If I can make a request, even if it's by design, could you at least add a note to the rftools dimensions pages saying if you are not adding a custom way to get to dimensions, then you need Utilities? I had put together a modpack about a month ago, and I was only just told by a player that we were missing parts to use the custom dimensions. While I think not marking it as a dependency is fine, please make a note so people who aren't aware that it's missing parts can be.
