### ISSUE TITLE
RFtools thinking other mods dimensions are not powered 

### ISSUE THREAD

**Issue by dmodoomsirius** [McJty/RFToolsDimensions#45]
RFtools thinking other mods dimensions are not powered and resulting in players death https://github.com/zmaster587/AdvancedRocketry/issues/250

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
Both Mods , RFTOOLSDIMS  and ADVANCED ROCKETRY use the SAME DIM ID's,
in AR dims you will find RFTOOLS little dimlet houses.
My private opinion: RFTOOLSDIM was first, so AR should change the DIM ID's
regards

**Comment by McJty** [comment]
Well AR should check if a dimension is already registered before trying to use it

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
the proposed ( by zmaster587) config settings in advancedRocketry.cfg;
I:minDimension=2000
did not change anything, using a NEW TEST WORLD in creative 
same low DIM ID's as before, no offset at all

**Comment by zmaster587** [comment]
I do check check if a dimension is in use before the planet dimids are selected, https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L185 (this method is called from the planet generation code, which in turn is called at post init, perhaps there is a better way to perform a check, but I had assumed any dimsion already is use would be registered with Forge, otherwise, if registered after, check before registering).

As I requested on the tracker for AR, I have been looking through the code for RFTools and the dimension addon for quite some time and have not found any checks to see if a dimension is registered, would you please be so kind as to at least give the name of the class the checks are in, I'm trying to debug this and I'm trying to determine if it's a timing issue or not, and if so how to fix, but without knowing when the check is made in the other mod it is rather difficult.  I'll continue looking for it, but so far looking for any references to the vanilla DimensionManager has only turned up packet handing code and the unregisterAll function. 

 @ThisIsTheGitHubAccount4MUHAKL your post on the AR tracker indicates otherwise, the information you listed shows you went to dimension 138, which is not exactly doing nothing at all.

**Comment by McJty** [comment]
The code where this is checked can be found here:

https://github.com/McJty/RFToolsDimensions/blob/1.10/src/main/java/mcjty/rftoolsdim/dimensions/RfToolsDimensionManager.java

Basically in createNewDimension(). The important call is:
            id = DimensionManager.getNextFreeDimId();
Which asks a new id from the forge dimension manager

**Comment by zmaster587** [comment]
Alright, thank you.  I somehow missed that.  Correct me if I'm wrong, but it looks like dimensions are created only through a command or an ingame machine, which of course, would be well after preinit?

I am also unable to even replicate the issue using the most recent builds on CF and can see no reason why a dimension conflict could exist in the first place short of manipulation from a third party.

**Comment by McJty** [comment]
You are right about dimension being created dynamically with a machine. So after postInit even

**Comment by zmaster587** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/250 looks like it was caused by adding AR after rftools dim anyway, but it took several days before  ThisIsTheGitHubAccount4MUHAKL to specify that AR was added to a preexisting world that already had RFTools.  So I think you were right on that.  I have not been able to replicate  ThisIsTheGitHubAccount4MUHAKL's issue other than with a pre-existing world, at which point, it is not an issue with RFToolsDimensions anyway.  So this issue can probably be closed.
